# Generated by Django 2.2 on 2019-04-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('dataNascita', models.DateField()),
                ('nazionalita', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Attore',
                'verbose_name_plural': 'Attori',
            },
        ),
        migrations.CreateModel(
            name='Genere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominazione', models.CharField(max_length=30)),
                ('img', models.URLField()),
            ],
            options={
                'verbose_name': 'Genere',
                'verbose_name_plural': 'Generi',
            },
        ),
        migrations.CreateModel(
            name='Regista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('dataNascita', models.DateField()),
                ('nazionalita', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Regista',
                'verbose_name_plural': 'Registi',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('annoUscita', models.DateField()),
                ('trama', models.TextField()),
                ('durata', models.FloatField()),
                ('lingua', models.CharField(max_length=20)),
                ('img', models.URLField()),
                ('url', models.URLField()),
                ('disponibile', models.BooleanField(default='true')),
                ('attori', models.ManyToManyField(to='Film.Attore')),
                ('generi', models.ManyToManyField(to='Film.Genere')),
                ('registi', models.ManyToManyField(to='Film.Regista')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Film',
            },
        ),
    ]
